version: 0.2

env:
  variables:
    APP_DIR: "app"
    BUILD_OUTPUT: "build"
    APP_NAME: "poc-web-app"

phases:
  pre_build:
    commands:
      - echo "Cleaning previous build output"
      - rm -rf $BUILD_OUTPUT
      - mkdir -p $BUILD_OUTPUT

  build:
    commands:
      - echo "Copying application files"
      - cp -r $APP_DIR/* $BUILD_OUTPUT/
      - ls -la $BUILD_OUTPUT

  post_build:
    commands:
      - echo "Running post-build validations"

      # 1️⃣ Validate required files
      - test -f $BUILD_OUTPUT/index.html || (echo "index.html missing" && exit 1)

      # 2️⃣ Create build metadata (very real-world)
      - |
        cat <<EOF > $BUILD_OUTPUT/build-info.json
        {
          "application": "${APP_NAME}",
          "build_id": "${CODEBUILD_BUILD_ID}",
          "commit_id": "${CODEBUILD_RESOLVED_SOURCE_VERSION}",
          "build_time": "$(date -u)"
        }
        EOF

      # 3️⃣ Final sanity check
      - echo "Final build output:"
      - ls -la $BUILD_OUTPUT

artifacts:
  base-directory: $BUILD_OUTPUT
  files:
    - '**/*'
