version: 0.2

env:
  variables:
    APP_DIR: "."                    # Root directory containing your app code
    DEPLOY_DIR: "/var/www/html"      # EC2 deployment path
    SERVER_USER: "ec2-user"          # EC2 SSH user
    SERVER_IP: "10.0.3.33" # Replace with dynamic or use SSM Parameter
    BUILD_ENV: "prod"                # Environment
    EC2_TAG_KEY: "Name"              # Tag key to identify EC2 instances
    EC2_TAG_VALUE: "your-instance"   # Tag value to identify EC2 instances

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Starting install phase..."
      - echo "Installing required packages..."
      - pip install --upgrade pip wheel
      - pip install paramiko  # Optional, if using Python for SSH/SSM

  pre_build:
    commands:
      - echo "Pre-build phase: cleaning old artifacts..."
      - rm -rf build/*
      - mkdir -p build
      - echo "Copying application files to build directory..."
      - cp -r $APP_DIR/* build/
      - echo "Build directory contents:"
      - ls -la build/

  build:
    commands:
      - echo "Build phase: preparing artifacts..."
      - echo "Build directory contents after copy:"
      - ls -la build/
      - echo "Build successful, ready for deployment."

  post_build:
    commands:
      - echo "Post-build: deploying to EC2 via SSM..."
      - echo "Deployment is triggered for EC2 instance with tag $EC2_TAG_KEY=$EC2_TAG_VALUE."
      - |
        # Find EC2 instance IDs using the provided tag key and value
        INSTANCES=$(aws ec2 describe-instances \
          --filters "Name=tag:$EC2_TAG_KEY,Values=$EC2_TAG_VALUE" \
          "Name=instance-state-name,Values=running" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text)
      - echo "Target EC2 Instances: $INSTANCES"
      - |
        # Loop through each instance and deploy using SSM
        for instance in $INSTANCES; do
          echo "Deploying to $instance..."
          aws ssm send-command \
            --targets "Key=InstanceIds,Values=$instance" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying build artifacts" \
            --parameters commands="rm -rf $DEPLOY_DIR/*; cp -r /tmp/build/* $DEPLOY_DIR/"
        done
      - echo "Deployment commands sent via SSM to EC2 instances."

artifacts:
  files:
    - '**/*'  # This is optional; include if you need to upload artifacts to S3
  base-directory: build  # The directory where your built files are stored
