version: 0.2

env:
  variables:
    APP_DIR: "."                     # repo root
    BUILD_DIR: "build"
    DEPLOY_DIR: "/var/www/html"      # EC2 deployment path
    BUILD_ENV: "prod"                # Environment
    EC2_TAG_KEY: "Name"
    EC2_TAG_VALUE: "poc-ec2"         # matches the EC2 Name tag
    SERVER_USER: "ec2-user"

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Install phase started..."
      - pip install --upgrade pip wheel
      - pip install paramiko boto3  # for optional SSM/SSH deployment

  pre_build:
    commands:
      - echo "Pre-build: cleaning old build directory..."
      - rm -rf $BUILD_DIR
      - mkdir -p $BUILD_DIR
      - echo "Listing repo contents:"
      - ls -la

  build:
    commands:
      - echo "Build: copying files from repo root to build folder..."
      - cp -r $APP_DIR/* $BUILD_DIR/
      - echo "Contents of build directory:"
      - ls -la $BUILD_DIR

  post_build:
    commands:
      - echo "Post-build: deploying to EC2 via SSM..."
      - |
        INSTANCES=$(aws ec2 describe-instances \
          --filters "Name=tag:$EC2_TAG_KEY,Values=$EC2_TAG_VALUE" \
          "Name=instance-state-name,Values=running" \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output text)
      - echo "Target EC2 Instances: $INSTANCES"
      - |
        for instance in $INSTANCES; do
          echo "Deploying to $instance..."
          aws ssm send-command \
            --targets "Key=InstanceIds,Values=$instance" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying build artifacts" \
            --parameters commands="rm -rf $DEPLOY_DIR/*; cp -r /tmp/build/* $DEPLOY_DIR/"
        done
      - echo "Deployment commands sent via SSM."
